name: bluetrack
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  path_provider: ^2.1.1
  flutter:
    sdk: flutter

  mqtt_client: ^9.6.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  modal_bottom_sheet: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  tuple: ^2.0.2
  page_transition: ^2.2.1
  shimmer: ^3.0.0
  permission_handler: ^12.0.0+1
  flutter_blue_plus: ^1.34.5
  geolocator: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/launcher/
    - assets/lottie/
    - assets/lang/
    - assets/certs/AmazonRootCA1.pem
    - assets/certs/1f517192598cbed5c547cb2b5b38eb14f31fe1aa33f4c1d7084057a348c18eb5-certificate.pem.crt
    - assets/certs/1f517192598cbed5c547cb2b5b38eb14f31fe1aa33f4c1d7084057a348c18eb5-private.pem.key
